#!/bin/ksh

# Variables
if [[ $# -eq 0 ]]; then
  DB="database.sqlite"
else
  DB="$1"
fi
SQL="sqlite3 "$DB
# End Variables

if [[ -f $DB ]]; then
  COMMAND="SELECT question,answer,rank FROM qandas;"
  # That's a <tab> character, so don't just copy-paste this code.
  echo $COMMAND | $SQL |sed 's/|/	/g'
fi
